import requests


def query_responses() -> list:
    texts = [
        "I will continue to work on the prototype that designs the user interface (UI)",
        "Continue to code the frontend interface (UI) of the dashboard",
        "Add new features to the UI",
        "Work to redesign parts of the UI/UX that users feedback",
        "Have a discussion with the team how the UI/UX flow should be",
        "Finalise making changes to the UI and open a PR to merge",
        "Roll out the newly designed UI",
        "Spin up a container to serve the cookiedough's frontend (UI).",
        "Continue to code the homepage design (UI) Design the UI for blob website",
        "Take down the frontend (UI) server and work on it as per the scheduled maintenance",
        "I will work on the UI for the website that the customer pot seller XXX request",
        "Troubleshoot faulty API endpoint at '/help/me'",
        "I will be moving the API designed in 2020 to the archive storage",
        "Design the different API endpoints for our apps to allow others to use its service",
        "Enable 50/50 traffic to old and new API to slowly migrate users",
        "Publish the API endpoints using Apigee Setup analysing of the APIs' at Apigee to track traffic spikes",
        "I will work to rearchitect the API endpoints that the business users has access to",
        "I will be working on the documentation for the API endpoints",
        "I will be focusing to minimise the downtime to migrate users to the new API endpoints",
        "I will have the APIs' to have a standardised specification using OpenAPI",
        "Will be working to fix the broken button that sends the API request",
        "I will be working on the logic to script spinning up the containers for unit testing",
        "I will write the logic to enable users to make submission of responses through the 'users/responses' endpoint",
        "I will be working on the serving logic so that users can make inference through the 'models/inference' endpoint",
        "I will be working on the logic that enables push notification to be sent upon user subscription",
        "I will be adding the backend logic to allocate points if user stays on our site for 5 mins",
        "Work on the logic to have a smooth edge when the animated cat ear folds",
        "Work on the logic to build a stop motion camera with Raspberry Pi",
        "I will continue to code the logic to animate the blobs movement based on users voice command",
        "I will work on the logic to make the clock tick when user press the left-arrow key button",
        "Work on the serving logic for BERT model",
        "Meet with stakeholders to go through the app's logic flow",
        "Continue to do the logic for payment plans for users to access different tiers of API usage",
        "Finalise the backend logic to pop a ballon when the users click on it",
        "Schedule a time with standupbento to discuss the logic flow for the chief app",
        "Debug the faulty logic that occurs during sign up for users",
        "I will be working on the backend maintenance of the app and resume the service once done",
        "I will be working to document the app features/functionalities and how it works"
    ]
    return texts
